export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE'

export const RESET_DATA_RECORD = 'RESET_DATA_RECORD'

export const ADD_RECORD_TYPE = 'ADD_RECORD_TYPE'

export const ADD_AUX_PARAMS_TO_RECORD = 'ADD_AUX_PARAMS_TO_RECORD'

export const ADD_FIELDS_TO_RECORD = 'ADD_FIELDS_TO_RECORD'

export const ADD_SUBLIST_TO_RECORD = 'ADD_SUBLIST_TO_RECORD'

export const UPDATE_RECORD_LINK = 'UPDATE_RECORD_LINK'
